#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  main.py
#  
#  Copyright 2016 Andrei Tumbar <atuser@Kronos>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  


import os, sys

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('GtkSource', '3.0')

from gi.repository import Gtk, GObject, GLib, GtkSource, Pango

class FileManager:
	
	buffers = []
	labels = []
	
	def __init__ ( self, _main_box ):
		self.main_box = _main_box
		self.notebook = Gtk.Notebook ( )
		self.main_box.add ( self.notebook )
	
	def get_bare_name ( self, string ):
		i = string.rfind ( "/" )
		return string [ i + 1: ]
	
	def open ( self, __file ):
		lm = GtkSource.LanguageManager.new ( )
		language = lm.guess_language ( __file, None )
		buffer = GtkSource.Buffer ( )
		
		if language:
			buffer.set_highlight_syntax ( True )
			buffer.set_language ( language )
		else:
			print ( "No language found for file '%s'" % __file )
			print ( "Using first line program" )
			
			buff = open ( __file, "r" ).readlines ( ) [ 0 ]
			try:
				buff.split ( " " ) [ 1 ]
			except IndexError:
				print ( "Language not found!" )
				buffer.set_highlight_syntax ( False )
			else:
				lan_name = buff.split ( " " ) [ 1 ]
				language = lm.guess_language ( "a.%s" % lan_name, None )
		
		buff_txt = open ( __file ).read ( )
		buffer.set_text ( buff_txt )
		buffer.place_cursor ( buffer.get_start_iter ( ) )
		sm = GtkSource.StyleSchemeManager.new ( )
		sm.append_search_path ( '/'.join ( ( os.path.dirname ( os.path.realpath ( __file__ ) ), "src/schemes" ) ) )
		
		style = sm.get_scheme ( "github" )
		buffer.set_style_scheme ( style )
		
		SOURCE = GtkSource.View.new_with_buffer ( buffer )
		SOURCE.set_auto_indent ( True )
		SOURCE.set_indent_on_tab ( True )
		SOURCE.set_show_line_numbers ( True )
		SOURCE.set_highlight_current_line ( True )
		
		fontdesc = Pango.FontDescription ( "Monospace 10.5" )
		SOURCE.override_font ( fontdesc )
		
		SOURCE.set_tab_width ( 4 )
		
		curr_scrolled = Gtk.ScrolledWindow ( )
		curr_scrolled.add ( SOURCE )
		curr_scrolled.set_hexpand ( True )
		curr_scrolled.set_vexpand ( True )
		
		label = Gtk.Label ( self.get_bare_name ( __file ) )
		self.notebook.prepend_page ( curr_scrolled, label )
		self.notebook.set_current_page ( 0 )
		self.notebook.show_all ( )

class BuilderSet ( object ):
	
	builder_dict = {}
	
	def __init__ ( self, directory ):
		self.directory = directory
	
	def new ( self, __file ):
		builder_buff = Gtk.Builder ( )
		builder_buff.add_from_file ( "%s/%s" % ( self.directory, __file ) )
		self.builder_dict [ __file ] = builder_buff
	
	def __getitem__ ( self, __name ):
		try:
			self.builder_dict [ __name ]
		except KeyError:
			print ( "Builder not initialized: '%s'" % __name )
			return
		
		return self.builder_dict [ __name ]

def new_template ( button ):
	MAIN.project.builders [ "main.ui" ].get_object ( "temp_name" ).set_text ( "" )
	MAIN.project.TemplateWindow.show_all ( )

def new_page ( button ):
	pass
	
def temp_ok ( button ):
	template_name = MAIN.project.builders [ "main.ui" ].get_object ( "temp_name" ).get_text ( )
	
	# Create the empty file
	open(template_name, 'a').close()
	
	MAIN.project.files.open ( template_name )
	MAIN.project.TemplateWindow.hide ( )

def temp_cancel ( button, *args ):
	MAIN.project.TemplateWindow.hide ( )

def __open__ ( button ):
	MAIN.project.file_chooser.show_all ( )

def file_changed ( file_dialog ):
	__file = file_dialog.get_filename ( )
	open_file ( __file )

def close_file_dia ( button ):
	MAIN.project.file_chooser.hide ( )

def open_file ( __file ):
	type_chooser = MAIN.project.builders [ "main.ui" ].get_object ( "type_chooser" )
	
	type_id = type_chooser.get_model ( ) [ type_chooser.get_active ( ) ] [ 1 ]
	
	MAIN.project.open ( __file, type_id )
	MAIN.project.file_chooser.hide ( )

def open_file_sig ( button ):
	open_file ( MAIN.project.builders [ "main.ui" ].get_object ( "filechooser" ).get_filename ( ) )

main_handlers = {
"exit": Gtk.main_quit,
"template": new_template,
"page": new_page,
"temp_ok": temp_ok,
"temp_cancel": temp_cancel,
"open": __open__,
"file_changed": file_changed,
"close_file_dia": close_file_dia,
"open_file": open_file_sig
}

class Project:
	file_names = []
	file_types = []
	
	def __init__ ( self, start_doc, _dir, _type ):
		os.chdir ( os.path.dirname ( os.path.realpath ( __file__ ) ) )
		GObject.type_register ( GtkSource.View )
		
		self.builders = BuilderSet ( _dir )
		
		self.builders.new ( "main.ui" )
		self.builders [ "main.ui" ].connect_signals ( main_handlers )
		
		self.MainWindow = self.builders [ "main.ui" ].get_object ( "main" )
		self.TemplateWindow = self.builders [ "main.ui" ].get_object ( "new_temp_main" )
		self.file_chooser = self.builders [ "main.ui" ].get_object ( "filechooser" )
		self.file_chooser.set_transient_for ( self.MainWindow )
		
		self.files = FileManager ( self.builders [ "main.ui" ].get_object ( "main_box" ) )
		
		self.open ( start_doc, _type )
		
		self.MainWindow.show_all ( )
	
	# File types:
	#  template
	#  input
	#  config
	#  other
	def open ( self, __file, _type="input" ):
		self.files.open ( __file )
		
		self.file_names.append ( __file )
		self.file_types.append ( _type )

class main:
	
	template = ""
	config = ""
	pages = []
	other = []
	
	def __init__ ( self, start_file="src/parser.cpp", _dir="src/gui", start_type="input" ):
		self.project = Project ( start_file, _dir, start_type )
		
		if ( start_type == "input" ):
			self.pages.append ( start_file )
		elif ( start_type == "template" ):
			self.template = start_file
		elif ( start_type == "config" ):
			self.config = start_file
		elif ( start_type == "other" ):
			self.other.append ( start_file )
		else:
			raise ValueError ( "The following is not a file type: '%s'" % start_type )
		

global MAIN
MAIN = main ( )

Gtk.main ( )
